"""
Output section titles and generated block markers.

Generators and composers must import section labels from this catalog instead
of hardcoding generated block titles inside logic classes.
"""


DB2_INFRASTRUCTURE_MARKER = (
    "DB2 SQLCA, SQL ERROR WORKING STORAGE, DCLGEN INCLUDES, AND CURSOR FLAGS"
)


DB2_SQL_ERROR_LOCATION_MARKER = "DB2 SQL ERROR LOCATION"


DB2_CURSOR_FLAGS_MARKER = "DB2 CURSOR END-OF-CURSOR FLAGS"


DB2_CURSOR_DECLARATIONS_MARKER = "DB2 CURSOR DECLARATIONS"


DB2_CURSOR_PARAGRAPH_MARKER = "DB2 GENERATED CURSOR OPEN FETCH CLOSE PARAGRAPHS"


DB2_GENERATED_TIMESTAMP_MARKER = "DB2 GENERATED TIMESTAMP AND AUDIT WORKING STORAGE"


SQLERRWS_INCLUDE_NAME = "SQLERRWS"


SQLCA_INCLUDE_NAME = "SQLCA"


SQL_LOCATION_FIELD_NAME = "SQL-LOCATION"


SQL_LOCATION_PICTURE = "PIC X(40) VALUE SPACES."