import re

from catalogs.output_sections import DB2_CURSOR_PARAGRAPH_MARKER
from idms_db2_phase2.domain.models import IdmsOperation
from idms_db2_phase2.generators.db2_infrastructure_generator import (
    Db2InfrastructureGenerator,
)
from idms_db2_phase2.generators.sql_error_generator import SqlErrorGenerator
from idms_db2_phase2.resolvers.host_variable_resolver import HostVariableResolver
from patterns.db2_patterns import END_PROGRAM_PATTERN


class CursorParagraphGenerator:
    """
    Generates DB2 cursor OPEN / FETCH / CLOSE paragraphs.

    Important:
    - Cursor declarations are generated by Db2InfrastructureGenerator.
    - FETCH INTO host variables must match the SELECT columns used in those
      declarations.
    - Therefore this generator reuses
      db2_infrastructure_generator.last_cursor_specs whenever available.
    """

    SQLERROR_PARAGRAPH_NAME = "SQLERROR"

    def __init__(
        self,
        db2_infrastructure_generator: Db2InfrastructureGenerator,
        host_variable_resolver: HostVariableResolver,
        sql_error_generator: SqlErrorGenerator,
    ) -> None:
        self.db2_infrastructure_generator = db2_infrastructure_generator
        self.host_variable_resolver = host_variable_resolver
        self.sql_error_generator = sql_error_generator
        self.messages: list[str] = []

    def apply(
        self,
        cobol_text: str,
        operations: list[IdmsOperation],
    ) -> tuple[str, list[str]]:
        self.messages = []

        text = str(cobol_text or "")

        if not text:
            return text, self.messages

        cursor_specs = self._cursor_specs(
            operations=operations,
        )

        if not cursor_specs:
            self.messages.append(
                "DB2 cursor paragraphs: no cursor operations found."
            )
            return text, self.messages

        sql_error_paragraph = self.SQLERROR_PARAGRAPH_NAME

        updated_text = self._normalize_existing_sql_error_references(text)

        updated_text = self._rewrite_cursor_perform_calls(
            text=updated_text,
            cursor_specs=cursor_specs,
        )

        if DB2_CURSOR_PARAGRAPH_MARKER in updated_text:
            self.messages.append(
                "DB2 cursor paragraphs: generated cursor paragraph block already exists."
            )
            return updated_text, self.messages

        block = self.paragraph_block(
            cursor_specs=cursor_specs,
            sql_error_paragraph=sql_error_paragraph,
        )

        updated_text = self._insert_paragraph_block(
            text=updated_text,
            block=block,
        )

        self.messages.append(
            f"DB2 cursor paragraphs: generated {len(cursor_specs)} cursor paragraph set(s)."
        )

        for spec in cursor_specs:
            if not list(spec.get("host_variables", [])):
                self.messages.append(
                    "DB2 cursor paragraphs: no FETCH host variables resolved for "
                    f"cursor {spec.get('cursor_name', '')} "
                    f"record {spec.get('record_name', '')} "
                    f"table {spec.get('table_name', '')}."
                )

        return updated_text, self.messages

    def _cursor_specs(
        self,
        operations: list[IdmsOperation],
    ) -> list[dict[str, object]]:
        cached_specs = getattr(
            self.db2_infrastructure_generator,
            "last_cursor_specs",
            [],
        )

        if cached_specs:
            return cached_specs

        return self.db2_infrastructure_generator.cursor_specs(
            operations
        )

    def paragraph_block(
        self,
        cursor_specs: list[dict[str, object]],
        sql_error_paragraph: str,
    ) -> str:
        lines: list[str] = []

        lines.extend(
            self._comment_block(DB2_CURSOR_PARAGRAPH_MARKER)
        )

        lines.append("")

        for spec in cursor_specs:
            cursor_name = str(spec.get("cursor_name", ""))
            open_paragraph = str(spec.get("open_paragraph", ""))
            fetch_paragraph = str(spec.get("fetch_paragraph", ""))
            close_paragraph = str(spec.get("close_paragraph", ""))
            host_variables = list(spec.get("host_variables", []))

            if not cursor_name:
                continue

            if open_paragraph:
                lines.extend(
                    self.open_paragraph(
                        cursor_name=cursor_name,
                        paragraph_name=open_paragraph,
                        sql_error_paragraph=sql_error_paragraph,
                    )
                )
                lines.append("")

            if fetch_paragraph:
                lines.extend(
                    self.fetch_paragraph(
                        cursor_name=cursor_name,
                        paragraph_name=fetch_paragraph,
                        host_variables=host_variables,
                        sql_error_paragraph=sql_error_paragraph,
                    )
                )
                lines.append("")

            if close_paragraph:
                lines.extend(
                    self.close_paragraph(
                        cursor_name=cursor_name,
                        paragraph_name=close_paragraph,
                        sql_error_paragraph=sql_error_paragraph,
                    )
                )
                lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    def open_paragraph(
        self,
        cursor_name: str,
        paragraph_name: str,
        sql_error_paragraph: str,
    ) -> list[str]:
        return [
            f"{paragraph_name}.",
            f"MOVE '{paragraph_name}' TO SQL-LOCATION.",
            "EXEC SQL",
            f"    OPEN {cursor_name}",
            "END-EXEC.",
            "EVALUATE SQLCODE",
            "    WHEN ZERO",
            f"        SET {cursor_name}-NOT-EOC TO TRUE",
            "    WHEN OTHER",
            f"        DISPLAY 'ERROR WHILE OPENING CURSOR {cursor_name}'.",
            f"        PERFORM {sql_error_paragraph}.",
            "END-EVALUATE.",
        ]

    def fetch_paragraph(
        self,
        cursor_name: str,
        paragraph_name: str,
        host_variables: list[str],
        sql_error_paragraph: str,
    ) -> list[str]:
        lines: list[str] = [
            f"{paragraph_name}.",
            f"MOVE '{paragraph_name}' TO SQL-LOCATION.",
            "EXEC SQL",
            f"    FETCH {cursor_name}",
        ]

        clean_hosts = self._clean_host_variables(host_variables)

        if clean_hosts:
            lines.append("    INTO")
            lines.extend(
                self._fetch_host_lines(clean_hosts)
            )

        lines.extend(
            [
                "END-EXEC.",
                "EVALUATE SQLCODE",
                "    WHEN ZERO",
                "        CONTINUE",
                "    WHEN 100",
                f"        SET {cursor_name}-EOC TO TRUE",
                "    WHEN OTHER",
                f"        DISPLAY 'ERROR WHILE FETCHING CURSOR {cursor_name}'.",
                f"        PERFORM {sql_error_paragraph}.",
                "END-EVALUATE.",
            ]
        )

        return lines

    def close_paragraph(
        self,
        cursor_name: str,
        paragraph_name: str,
        sql_error_paragraph: str,
    ) -> list[str]:
        return [
            f"{paragraph_name}.",
            f"MOVE '{paragraph_name}' TO SQL-LOCATION.",
            "EXEC SQL",
            f"    CLOSE {cursor_name}",
            "END-EXEC.",
            "EVALUATE SQLCODE",
            "    WHEN ZERO",
            "        CONTINUE",
            "    WHEN OTHER",
            f"        DISPLAY 'ERROR WHILE CLOSING CURSOR {cursor_name}'.",
            f"        PERFORM {sql_error_paragraph}.",
            "END-EVALUATE.",
        ]

    def _rewrite_cursor_perform_calls(
        self,
        text: str,
        cursor_specs: list[dict[str, object]],
    ) -> str:
        updated = str(text or "")

        for spec in cursor_specs:
            cursor_name = str(spec.get("cursor_name", "")).strip()
            open_paragraph = str(spec.get("open_paragraph", "")).strip()
            fetch_paragraph = str(spec.get("fetch_paragraph", "")).strip()
            close_paragraph = str(spec.get("close_paragraph", "")).strip()

            if not cursor_name:
                continue

            replacements = {
                "OPEN": open_paragraph,
                "FETCH": fetch_paragraph,
                "CLOSE": close_paragraph,
            }

            for operation, target_paragraph in replacements.items():
                if not target_paragraph:
                    continue

                updated = self._replace_unnumbered_perform(
                    text=updated,
                    operation=operation,
                    cursor_name=cursor_name,
                    target_paragraph=target_paragraph,
                )

                updated = self._replace_numbered_perform(
                    text=updated,
                    operation=operation,
                    cursor_name=cursor_name,
                    target_paragraph=target_paragraph,
                )

            updated = self._replace_legacy_spec_perform_calls(
                text=updated,
                spec=spec,
            )

        return updated

    def _replace_unnumbered_perform(
        self,
        text: str,
        operation: str,
        cursor_name: str,
        target_paragraph: str,
    ) -> str:
        pattern = re.compile(
            rf"(?P<prefix>\bPERFORM\s+)"
            rf"{operation}-{re.escape(cursor_name)}"
            rf"(?P<suffix>\.?)",
            flags=re.IGNORECASE,
        )

        return pattern.sub(
            rf"\g<prefix>{target_paragraph}\g<suffix>",
            text,
        )

    def _replace_numbered_perform(
        self,
        text: str,
        operation: str,
        cursor_name: str,
        target_paragraph: str,
    ) -> str:
        pattern = re.compile(
            rf"(?P<prefix>\bPERFORM\s+)"
            rf"\d{{3}}-{operation}-{re.escape(cursor_name)}"
            rf"(?P<suffix>\.?)",
            flags=re.IGNORECASE,
        )

        return pattern.sub(
            rf"\g<prefix>{target_paragraph}\g<suffix>",
            text,
        )

    def _replace_legacy_spec_perform_calls(
        self,
        text: str,
        spec: dict[str, object],
    ) -> str:
        updated = str(text or "")

        legacy_replacements = {
            str(spec.get("old_open_paragraph", "")).strip(): str(
                spec.get("open_paragraph", "")
            ).strip(),
            str(spec.get("old_fetch_paragraph", "")).strip(): str(
                spec.get("fetch_paragraph", "")
            ).strip(),
            str(spec.get("old_close_paragraph", "")).strip(): str(
                spec.get("close_paragraph", "")
            ).strip(),
        }

        for old_paragraph, new_paragraph in legacy_replacements.items():
            if not old_paragraph:
                continue

            if not new_paragraph:
                continue

            if old_paragraph == new_paragraph:
                continue

            pattern = re.compile(
                rf"(?P<prefix>\bPERFORM\s+)"
                rf"{re.escape(old_paragraph)}"
                rf"(?P<suffix>\.?)",
                flags=re.IGNORECASE,
            )

            updated = pattern.sub(
                rf"\g<prefix>{new_paragraph}\g<suffix>",
                updated,
            )

        return updated

    def _normalize_existing_sql_error_references(
        self,
        text: str,
    ) -> str:
        updated = str(text or "")

        updated = re.sub(
            r"\bPERFORM\s+SQL-ERROR\s*\.?",
            "PERFORM SQLERROR.",
            updated,
            flags=re.IGNORECASE,
        )

        updated = re.sub(
            r"(?m)^(\s*)(?:\d{6}\s+)?SQL-ERROR\.\s*(?:\d{8})?\s*$",
            r"\1SQLERROR.",
            updated,
            flags=re.IGNORECASE,
        )

        return updated

    def _clean_host_variables(
        self,
        host_variables: list[str],
    ) -> list[str]:
        output: list[str] = []

        for host in host_variables:
            clean_host = self.host_variable_resolver.normalize_host_reference(
                host
            )

            if not clean_host:
                continue

            if clean_host in output:
                continue

            output.append(clean_host)

        return output

    def _fetch_host_lines(
        self,
        host_variables: list[str],
    ) -> list[str]:
        output: list[str] = []

        for index, host in enumerate(host_variables):
            suffix = "," if index < len(host_variables) - 1 else ""
            output.append(f"        {host}{suffix}")

        return output

    def _insert_paragraph_block(
        self,
        text: str,
        block: str,
    ) -> str:
        end_program_match = END_PROGRAM_PATTERN.search(text)

        if end_program_match:
            return (
                text[: end_program_match.start()].rstrip()
                + "\n\n"
                + block.rstrip()
                + "\n\n"
                + text[end_program_match.start():].lstrip()
            ).rstrip() + "\n"

        return text.rstrip() + "\n\n" + block.rstrip() + "\n"

    def _comment_block(
        self,
        title: str,
    ) -> list[str]:
        return [
            f"* {title:<62}*",
        ]